### ISSUE TITLE
Error: Cannot find module '../bin/builder'

### ISSUE THREAD

**Issue by DominikDary** [piyasde/NodeSocketIO#1]
When I checkout the code and run it with `node server.js`I'm getting this error:
module.js:340
    throw err;
          ^
Error: Cannot find module '../bin/builder'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at object.module.io (/Users/daryde/workspaces/node/NodeSocketIO/node_modules/socket.io/node_modules/socket.io-client/lib/io.js:156:18)
    at Object.<anonymous> (/Users/daryde/workspaces/node/NodeSocketIO/node_modules/socket.io/node_modules/socket.io-client/lib/io.js:206:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Any idea about how I can run the code?

I'm using node version v0.8.18 and npm version 1.2.2.

**Comment by piyasde** [comment]
The node_modules directory is expected to be in the directory of the project source. so that - socket.io and other dependency modules for 'http', 'url' and 'fs'. This type of error can happen when the dependencies are not installed in the folder as expected in default node.js setup. Re-installing the dependency modules should solve the problems.

Our Node version is - 0.10.5

Also important link, which is worth to read - 
http://stackoverflow.com/questions/9023672/nodejs-how-to-resolve-cannot-find-module-error

**Comment by DominikDary** [comment]
Thanks for the reply. It turned out that during reinstalling socket.io something was kind of recompiled/reinitialised and then I was able to run the code.
